baseURL = "https://wiki.bazadanni.com/"
languageCode = "en-us"
title = "Random Stuff Wiki"
theme = "primitive"
enableRobotsTXT = true

[services]
  [services.googleAnalytics]
    ID = "UA-59829770-23"

[taxonomies]
  tag = "tags"
